# Generated by Django 5.0.2 on 2024-02-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="like_count",
            field=models.BigIntegerField(default=0),
        ),
    ]
