# Generated by Django 5.0.2 on 2024-02-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_post_like_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="like_count",
            field=models.BigIntegerField(default="0"),
        ),
    ]
