# Generated by Django 5.0.2 on 2024-02-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_alter_post_options_comments"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comments",
            name="user",
        ),
        migrations.AddField(
            model_name="comments",
            name="posted_by",
            field=models.CharField(default="1", max_length=100),
            preserve_default=False,
        ),
    ]
