# Generated by Django 5.0.2 on 2024-02-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_alter_comments_posted_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="created",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
